require("mapping.editor")
require("mapping.spellcheck")
require("mapping.tab_buffer")
require("mapping.highlighting")
require("mapping.terminal")
require("mapping.lspconfig")
require("mapping.tree")
require("mapping.trouble")
