require('mapping/spellcheck')
require('mapping/tab_buffer')
require('mapping/highlighting')
require('mapping/terminal')
require('mapping/lspconfig')
require('mapping/autopairs')
require('mapping/tree')
